word_hub-WebApp/models.py
from flask_login import UserMixin
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import psycopg2
from sqlalchemy import create_engine

def create_table():
    conn = psycopg2.connect("dbname='my_app' user='postgres' password='123456' host='localhost' port='5432' ")
    cur=conn.cursor()
    cur.execute('CREATE TABLE IF NOT EXISTS data2 (id INT NOT NULL IDENTITY PRIMARY KEY, email_ VARCHAR(120) UNIQUE, password_ VARCHAR(20))')
    conn.commit()
    conn.close()

db = SQLAlchemy()

class Data(db.Model, UserMixin):
    __tablename__='data2'
    id=db.Column(db.Integer, primary_key=True)
    email_=db.Column(db.String(120),unique=True)
    password_=db.Column(db.String(20))

    def __init__(self,email_,password_):
        self.email_=email_
        self.password_= password_

def create_app():  
    app=Flask(__name__)
    app.config['SECRET_KEY'] = 'hjhjhjhjhhjh'
    app.config['SQLALCHEMY_DATABASE_URI']=''
    db.init_app(app)

    from views import views
    app.register_blueprint(views, url_prefix="/")

    login_manager = LoginManager()
    login_manager.login_view = 'login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Data.query.get(int(id))
    
    return app

  

word_hub-WebApp/app.py
from models import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

word_hub-WebApp/views.py
from flask import Blueprint, flash, render_template,request
from send_email import send_email
from translate import *
from models import *
from quotes import get_quote
from dictionary import *
from flask_login import login_user, login_required, logout_user, current_user
#MySql will use mysql.connector

views = Blueprint("views",__name__)

@views.route("/logout")
@login_required
def logout():
    logout_user()
    return render_template('login.html', text='Logged Out')

@views.route('/')
def index():
    return render_template('login.html')

@views.route('/login', methods=['POST','GET'])
def login():
    if request.method=='POST':
        email=request.form['email_name']
        password=request.form['password_name']
        user = Data.query.filter_by(email_=email).first()
        if user:
            if user.password_ == password:
                login_user(user,remember=True)
                return render_template("home.html")
            else:
                return render_template('login.html', text='Password is incorrect')
        else:
            return render_template('login.html', text='User does not exist')
    return render_template("login.html", user=current_user)


@views.route('/signup', methods=['POST','GET'])
def signup():
    if request.method=='POST':
        email=request.form['email_name']
        password=request.form['password_name']
        password2=request.form['password_name2']
        user = Data.query.filter_by(email_=email).first()
        if user:
            return render_template('signup.html', 
                    text='Opps, email already exists')
        elif password != password2:
                return render_template('signup.html', 
                        text='Opps, Passwords dont match')
        else:
            new_user = Data(email_=email, password_=password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
        return render_template('login.html',text='Signed Up Successfully')
    return render_template('signup.html')


@views.route('/forgotpassword', methods=['POST','GET'])
def forgotpassword():
    if request.method=='POST':
        email=request.form['email_name']
        if db.session.query(Data).filter(Data.email_==email).count() == 0:
            return render_template('forgotpassword', 
                    text='Opps, email does not exists')
        else:
            user = Data.query.filter_by(email_=email).first()
            x = user.password_
            send_email(email,x)
            return render_template('login.html', text='Your Password is on its way')
    return render_template('forgotpassword.html')

@views.route("/home", methods=['POST','GET'])
@login_required
def home():
    if request.method=='POST':
        feel=request.form['feel']
        text = get_quote(feel)
        return render_template('home.html', text=text)
    return render_template('home.html')

@views.route("/dictionary", methods=['POST','GET'])
@login_required
def dictionary():
    if request.method=='POST':
        word=request.form['word']
        text = diction(word)
        return render_template('dictionary.html', text=text)
    return render_template('dictionary.html')

@views.route("/dictionary2", methods=['POST','GET'])
@login_required
def dictionary2():
    if request.method=='POST':
        word2=request.form['word2']
        text = diction2(word2)
        return render_template('dictionary.html', text2=text)
    return render_template('dictionary.html')

@views.route("/translate", methods=['POST','GET'])
@login_required
def translate():
    if request.method=='POST':
        dest=request.form['languages']
        input=request.form['input']
        output = trans(input,dest)
        return render_template('translate.html',input=input, output=output)
    return render_template('translate.html')

word_hub-WebApp/templates/base.html
<!DOCTYPE html>
<html land="'en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Word Hub</title>
    <head>
        <link href="../static/main.css" rel="stylesheet">
    </head>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    </body>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if not current_user.is_authenticated %}
                <a class="nav-item nav-link" id="login" href="/login">Log In</a>
                <a class="nav-item nav-link" id="signup" href="/signup">Sign Up</a>
                <a class="nav-item nav-link" id="forgotpassword"  href="/forgotpassword">Forgot Password</a>
                {% else %}
                <div class="dropdown">
                    <button class="dropbtn">Apps</button>
                    <div class="dropdown-content">
                      <a href="/home">Home</a>
                      <a href="/translate">Translator</a>
                      <a href="/dictionary">Dictionary</a>
                    </div>
                  </div>
                <a class="nav-item nav-link" id="logout"  href="/logout">Log Out</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">{%block content %} {% endblock %} </div>
</html>

word_hub-WebApp/templates/dictionary.html
{%extends "base.html"%}
{% block content %}
<head>
    <link href="../static/main.css" rel="stylesheet">
</head>
<body>
    <div class='container'>
        <h1>Dictionary</h1> 
        <h3>Enter a word to be translated</h3>
         <form action="{{url_for('views.dictionary')}}" method="POST">
             <input value="{{request.form['word']}}" type="text" name="word"> <br>   
            </form>
         <div class="quote">
           {{text | safe}}
        </div>
          {% if 'did you mean' in text|safe %}
        <form action="{{url_for('views.dictionary2')}}" method="POST">
            <input type="text" name="word2"> <br>   
           </form>
          {% else %}
          {% endif %}
          <div class="quote">
            {{text2 | safe}}
        </div>
    </div>   
</body>
{%endblock%}

word_hub-WebApp/templates/download.html
<!DOCTYPE html>
<html lang="'en">
    <div class="download">
        <a href= {{url_for('views.download')}} target="blank"><button class='btn'>Download</button></a>
    </div>
</html>

word_hub-WebApp/templates/forgotpassword.html
{%extends "base.html"%}
{% block content %}
    <body>
        <div class='container'>
            <h1>Forgot Password</h1>
            <h3>Please enter your email address below</h3>
            <div class="message">
                {{text | safe}}
            </div>
            <form action="{{url_for('views.forgotpassword')}}" method="POST">
                <input placeholder="enter your email address" type="email" name="email_name" required> <br>
            <div class="selector">
                <button type="submit" name="action" value="password">Retrieve Password</button> 
            </div>
            </form>
        </div>   
    </body>
</html>
{%endblock%}

word_hub-WebApp/templates/home.html
{%extends "base.html"%}
{% block content %}
    <head>
        <link href="../static/main.css" rel="stylesheet">
    </head>
    <body>
        <div class='container'>
            <h1>Home</h1>
            <h3>How do you fell today?</h3>
             <form action="{{url_for('views.home')}}" method="POST">
                 <input placeholder="Happy, Sad or Unloved" type="text" name="feel"> <br>   
                </form>
             <div class="quote">
                {{text | safe}}
            </div>
        </div>   
    </body>
{%endblock%}

word_hub-WebApp/templates/login.html
{%extends "base.html"%} 
{% block content %}
    <body>
        <div class='container'>
            <h1>Welcome To Word Hub </h1>
            <h3>Please enter your login details or sign up</h3>
           <div class="message">
               {{text | safe}}
           </div>
            <form action="{{url_for('views.login')}}" method="POST">
                <input title="Your data will be safe with us" placeholder="enter your email address" type="email" name="email_name" required> <br>
                <input title="Your data will be safe with us" placeholder="enter your password" type="password" name="password_name"  required> <br>
                <button type="submit" name="action" value="login">Login</button> 
            </form>
        </div>   
    </body>
{% endblock %}

word_hub-WebApp/templates/signup.html
{%extends "base.html"%} {% block title %}Blaines Website{% endblock %} 
{% block content %}
    <body>
        <div class='container'>
            <h1>Sign Up</h1>
            <h3>Please enter your details below</h3>
            <div class="message">
                {{text | safe}}
            </div>
            <form action="{{url_for('views.signup')}}" method="POST">
                <input placeholder="enter your email address" type="email" name="email_name" required> <br>
                <input placeholder="enter your password" type="password" name="password_name"  required> <br>
                <input placeholder="retype your password" type="password" name="password_name2"  required> <br>
                <button type="submit" name="action" value="signup">Sign Up</button> 
            </form>
        </div>
    </body>
</html>
{%endblock%}

word_hub-WebApp/templates/translate.html
{%extends "base.html"%}
{% block content %}
    <head>
        <link href="../static/main.css" rel="stylesheet">
    </head>
    <h1>Translator</h1> 
    <h3>Enter a text and select translation language</h3>
    <div class="translate">
        <form action="{{url_for('views.translate')}}" method="post">
                <textarea class="form-control" rows="10" placeholder="enter text..." name="input">{{input}}</textarea> <br>
                <textarea class="form-control" rows="10" placeholder="translated text..." name="output">{{output}}</textarea> <br>
                <button type="submit">Translate</button> 
                <select name='languages' class="form-default" style="width: 80px; height: 30px; font-size:15px;">
                    <option value="de">German</option>
                    <option value="fr">French</option>
                    <option value="es">Spanish</option>
                    <option value="pl">Polish</option>  
                </select>  
        </form>
    </div>
{%endblock%}